# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-18 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegister',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=30)),
                ('a_pwd', models.CharField(max_length=30)),
                ('a_sex', models.CharField(max_length=5)),
                ('a_number', models.CharField(max_length=20)),
                ('a_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('au_id', models.AutoField(primary_key=True, serialize=False)),
                ('au_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bk_id', models.AutoField(primary_key=True, serialize=False)),
                ('bk_name', models.CharField(max_length=30)),
                ('price', models.FloatField(max_length=30)),
                ('intro', models.CharField(max_length=300)),
                ('img', models.CharField(max_length=100)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainproject.Authors')),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('bt_id', models.AutoField(primary_key=True, serialize=False)),
                ('bt_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow_books',
            fields=[
                ('bb_id', models.AutoField(primary_key=True, serialize=False)),
                ('bb_bdate', models.DateField(auto_now=True)),
                ('bb_rdate', models.DateField(auto_now=True)),
                ('bk_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainproject.Books')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow_persons',
            fields=[
                ('bp_id', models.AutoField(primary_key=True, serialize=False)),
                ('bp_name', models.CharField(max_length=30)),
                ('bp_books', models.ManyToManyField(to='mainproject.Books')),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('upwd', models.CharField(max_length=30)),
                ('usex', models.CharField(max_length=5)),
                ('unumber', models.CharField(max_length=20)),
                ('uphone', models.CharField(max_length=15)),
                ('bp_professions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainproject.Professions')),
            ],
        ),
        migrations.AddField(
            model_name='borrow_books',
            name='bp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainproject.Borrow_persons'),
        ),
        migrations.AddField(
            model_name='books',
            name='bt_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainproject.BookType'),
        ),
        migrations.AddField(
            model_name='books',
            name='presses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainproject.Press'),
        ),
    ]
